api:
  dashboard: false
core:
  defaultRuleSyntax: v3
entryPoints:
  dns-tcp:
    address: :53/tcp
  dns-udp:
    address: :53/udp
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: :443
global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: INFO
ping: {}
providers:
  providersThrottleDuration: 2s
  docker:
    defaultRule:
      "Host(`{{ index .Labels \"com.docker.compose.service\"}}\
      .{{ env \"DOMAIN\" }}`)"
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: dns
    watch: true
serversTransport:
  insecureSkipVerify: true
