api:
  dashboard: false
entryPoints:
  dns_tcp:
    address: :53/tcp
  dns_udp:
    address: :53/udp
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: :443
global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: INFO
ping: {}
providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    network: compose_docker
    defaultRule:
      "Host(`{{ index .Labels \"com.docker.compose.service\"}}\
      .{{ env \"DOMAIN\" }}`)"
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false
serversTransport:
  insecureSkipVerify: true
