---
apt_install_packages:
  - name: acl

print_facts: false

docker_users:
  - "{{ user_info.name }}"

users:
  - username: pihole
    comment: Pi-Hole User
    shell: /bin/bash
    ssh_key: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN1YdxBpNlzxDqfJyw/QKow1F+wvG9hXGoqiysfJOn5Y vagrant insecure public key
    exclusive_ssh_key: yes
    use_sudo: yes
    use_sudo_nopass: yes
    user_state: present
    servers:
      - all
