---
print_facts: false

arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

cfssl_services:
  - pihole
  - traefik
cfssl_ca:
  CN: "{{ certificate_cn }}"
  key:
    algo: rsa
    size: 4096
  names:
    - C: US
      ST: UT
      L: Salt Lake City
      O: Example
cfssl_config:
  signing:
    default:
      expiry: 8760h
    profiles:
      client:
        usages:
          - signing
          - digital signature
          - key encipherment
          - client auth
        expiry: 8760h
      server:
        usages:
          - signing
          - digital signature
          - key encipherment
          - server auth
        expiry: 8760h

compose_directory: /dkr
compose_project_name: pihole
compose_user: "{{ users[0].username }}"
container_tags:
  - name: cfssl
    tag: v1.6.5
  - name: cloudflared
    tag: 2025.2.0
  - name: pihole
    tag: 2025.02.4
  - name: traefik
    tag: v3.3.3
  - name: wireguard
    tag: 1.0.20210914

docker_network:
  enable_ipv6: false
  subnet:
    ipv4: 172.20.0.0/24
    ipv6: fd00:1101:1001:10::/64
  cloudflared:
    ipv4: 172.20.0.250
  pihole:
    ipv4: 172.20.0.251
  wireguard:
    subnet:
      ipv4: 172.21.0.0/24
    port: 51820
docker_users:
  - "{{ compose_user }}"
domain: example.net

htpasswd_credentials:
  - path: "{{ traefik_directory_result.path }}/usersfile"
    owner: "{{ compose_user }}"
    group: "{{ compose_user }}"
    mode: "0644"
    users:
      - username: traefik
        password: "{{ traefik_htpasswd | default('traefik') }}"
        crypt_scheme: apr_md5_crypt

pihole_env:
  BLOCK_ICLOUD_PR: "true"
  CORS_HOSTS: ${PIHOLE_CORS:-local}
  DNSMASQ_LISTENING: "all"
  FTLCONF_IGNORE_LOCALHOST: "true"
  FTLCONF_MAXDBDAYS: "42"
  FTLCONF_MAXLOGAGE: "8.0"
  FTLCONF_PRIVACYLEVEL: "3"
  FTLCONF_webserver_api_password: ${WEBPASSWORD}
  FTLCONF_dns_upstreams: "{{ docker_network.cloudflared.ipv4 }}"

upstream_dns:
  - 1.1.1.3
  - 1.0.0.3

users:
  - username: pihole
    comment: Pi-Hole User
    shell: /bin/bash
    exclusive_ssh_key: true
    ssh_key: "{{ ssh_pub_key }}"
    use_sudo: true
    use_sudo_nopass: true
    user_state: present
    servers:
      - all

pihole:
  external_dns: false
  ssl: true
traefik:
  enable_dashboard: true
  enable_htpasswd: true
  enable_metrics: true
  use_letsencrypt: false
wireguard:
  enabled: true

sysctl_forward: >-
  {{
    sysctl_forward_ipv4 +
    (sysctl_forward_ipv6 if docker_network.enable_ipv6 else [])
  }}

sysctl_forward_ipv4:
  - name: net.ipv4.ip_forward
    value: "1"

sysctl_forward_ipv6:
  - name: net.ipv6.conf.all.forwarding
    value: "1"
