---
print_facts: false

docker_users:
  - "{{ users[0].username }}"

users:
  - username: pihole
    comment: Pi-Hole User
    shell: /bin/bash
    exclusive_ssh_key: yes
    ssh_key: "{{ vagrant_insecure_pub_key }}"
    use_sudo: yes
    use_sudo_nopass: yes
    user_state: present
    servers:
      - all
