---
print_facts: false

ansible_user: "{{ users[0].username }}"

cfssl_services:
  - pihole
  - traefik
cfssl_ca:
  CN: "{{ domain }}"
  key:
    algo: rsa
    size: 4096
  names:
    - C: US
      ST: UT
      L: Salt Lake City
      O: Example
cfssl_config:
  signing:
    default:
      expiry: 8760h
  profiles:
    client:
      usages:
        - signing
        - key encipherment
        - client auth
      expiry: 8760h
    server:
      usages:
        - signing
        - key encipherment
        - client auth
        - server auth
      expiry: 8760h

compose_directory: /dkr
compose_project_name: pihole

container_tags:
  - name: cfssl
    tag: v1.6.5
  - name: cloudflared
    tag: 2025.1.0
  - name: pihole
    tag: 2024.07.0
  - name: traefik
    tag: v3.3.2
  - name: wireguard
    tag: 1.0.20210914

domain: example.net
docker_users:
  - "{{ ansible_user }}"

users:
  - username: pihole
    comment: Pi-Hole User
    shell: /bin/bash
    exclusive_ssh_key: true
    ssh_key: "{{ ssh_pub_key }}"
    use_sudo: true
    use_sudo_nopass: true
    user_state: present
    servers:
      - all

pihole_external_dns: false
wireguard_enabled: true
