---
print_facts: false

cfssl_services:
  - pihole
  - traefik
cfssl_ca:
  CN: "{{ certificate_cn }}"
  key:
    algo: rsa
    size: 4096
  names:
    - C: US
      ST: UT
      L: Salt Lake City
      O: Example
cfssl_config:
  signing:
    default:
      expiry: 8760h
    profiles:
      client:
        usages:
          - signing
          - digital signature
          - key encipherment
          - client auth
        expiry: 8760h
      server:
        usages:
          - signing
          - digital signature
          - key encipherment
          - server auth
        expiry: 8760h

compose_directory: /dkr
compose_project_name: pihole
compose_user: "{{ users[0].username }}"
container_tags:
  - name: cfssl
    tag: v1.6.5
  - name: cloudflared
    tag: 2025.1.0
  - name: pihole
    tag: 2024.07.0
  - name: traefik
    tag: v3.3.3
  - name: wireguard
    tag: 1.0.20210914

docker_network:
  enable_ipv6: false
  subnet:
    ipv4: 172.20.0.0/24
    ipv6: fd00:1101:1001:10::/64
  cloudflared:
    ipv4: 172.20.0.250
  pihole:
    ipv4: 172.20.0.251
  wireguard:
    subnet:
      ipv4: 172.21.0.0/24
  wireguard_port: 51820
docker_users:
  - "{{ compose_user }}"
domain: example.net

pihole_env:
  CORS_HOSTS: ${PIHOLE_CORS:-local}
  DNSMASQ_LISTENING: "all"
  FTLCONF_IGNORE_LOCALHOST: "true"
  FTLCONF_MAXDBDAYS: "42"
  FTLCONF_MAXLOGAGE: "8.0"
  FTLCONF_PRIVACYLEVEL: "3"
  PIHOLE_DNS_: "{{ docker_network.cloudflared.ipv4 }}"
  WEBPASSWORD: ${WEBPASSWORD}

upstream_dns:
  - 1.1.1.3
  - 1.0.0.3

users:
  - username: pihole
    comment: Pi-Hole User
    shell: /bin/bash
    exclusive_ssh_key: true
    ssh_key: "{{ ssh_pub_key }}"
    use_sudo: true
    use_sudo_nopass: true
    user_state: present
    servers:
      - all

use_letsencrypt: false
pihole_external_dns: false
pihole_ssl: true
traefik_enable_dashboard: false
wireguard_enabled: true
