---

- name: Create docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_directory }}/docker-compose.yml"
    mode: '0644'
  register: compose_result

- name: Setup cfssl container and generate certificates
  ansible.builtin.include_tasks: cfssl.yml
  tags:
    - cfssl
    - config
    - certificates

