---

- name: Setup traefik container
  tags:
    - config
    - traefik
  block:
    - name: Create directory for traefik config
      ansible.builtin.file:
        name: "{{ compose_directory_result.path }}/traefik/config"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      register: traefik_directory_result
    - name: Template traefik config files
      ansible.builtin.template:
        src: traefik.yaml.j2
        dest: "{{ traefik_directory_result.path }}/traefik.yaml"
        mode: "0644"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
