---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache on Debian systems.
      ansible.builtin.apt:
        update_cache: true
        name: acl
      when: ansible_os_family == "Debian"
