---
- name: Pi-Hole Docker
  become: true
  become_method: ansible.builtin.sudo
  hosts: all
  gather_facts: true
  tasks:
    - name: Create default system user
      ansible.builtin.include_role:
        name: ryandaniels.users
      tags:
        - user
    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
  vars_files:
    - vars/vars.yml
