---
- name: Pi-Hole Docker
  become: true
  become_method: ansible.builtin.sudo
  hosts: all
  gather_facts: true
  handlers:
    - name: Restart resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted
  pre-tasks:
    - name: Get public key
      community.crypto.openssh_keypair:
        keyfile: "{{ openssh_keyfile }}"
        key_format: openssh
      register: key_result
  tasks:
    - name: Create default system user
      ansible.builtin.include_role:
        name: ryandaniels.users
      tags:
        - user
    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
    - name: Disable resolved stub listener
      ansible.builtin.replace:
        path: /etc/systemd/resolved.conf
        regexp: '#DNSStubListener=yes'
        replace: 'DNSStubListener=no'
      notify: Restart resolved
    - name: Replace resolv.conf
      block:
        - name: Check resolv.conf file
          ansible.builtin.stat:
            path: /etc/resolv.conf
          register: resolv_conf
        - name: Remove symlinked version
          ansible.builtin.file:
            path: /etc/resolv.conf
            state: absent
          when: resolv_conf.stat.islnk
        - name: Set DNS server in resolv.conf
          ansible.builtin.blockinfile:
            create: true
            mode: '0644'
            owner: root
            group: root
            path: /etc/resolv.conf
            block: |
              nameserver 127.0.0.1
              nameserver 1.1.1.1
              search lan
  vars_files:
    - vars/vars.yml
