---
- name: Pi-Hole Docker
  become: true
  become_method: ansible.builtin.sudo
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  handlers:
    - name: Restart resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted
    - name: Deploy stack
      community.docker.docker_compose_v2:
        project_name: "{{ compose_project_name }}"
        project_src: "{{ compose_directory }}"
        files:
          - docker-compose.yml
        state: present
  tasks:
    - name: Create System User
      ansible.builtin.include_role:
        name: ryandaniels.users
      tags:
        - user
    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
    - name: Disable resolved stub listener
      ansible.builtin.replace:
        path: /etc/systemd/resolved.conf
        regexp: '#DNSStubListener=yes'
        replace: 'DNSStubListener=no'
      notify: Restart resolved
    - name: Replace resolv.conf
      block:
        - name: Check resolv.conf file
          ansible.builtin.stat:
            path: /etc/resolv.conf
          register: resolv_conf
        - name: Remove symlinked version
          ansible.builtin.file:
            path: /etc/resolv.conf
            state: absent
          when: resolv_conf.stat.islnk
        - name: Set DNS server in resolv.conf
          ansible.builtin.blockinfile:
            create: true
            mode: '0644'
            owner: root
            group: root
            path: /etc/resolv.conf
            block: |
              nameserver 127.0.0.1
              {% for ns in upstream_dns %}
              nameserver {{ ns }}
              {% endfor %}
              search {{ domain }}
    - name: Set ip forwarding in the sysctl file
      when: wireguard.enabled
      block:
        - name: Enable ipv4 forwarding and reload
          ansible.posix.sysctl:
            name: net.ipv4.ip_forward
            value: '1'
            sysctl_set: true
            state: present
            reload: true
        - name: Enable ipv6 forwarding and reload
          ansible.posix.sysctl:
            name: net.ipv6.conf.all.forwarding
            value: '1'
            sysctl_set: true
            state: present
            reload: true
          when: docker_network.enable_ipv6
    - name: Setup compose project
      ansible.builtin.include_tasks: tasks/main.yml
  vars_files:
    - vars/vars.yml
